version: "3.4"
services:
  rust-server-test:
    build:
      context: .
      cache_from:
        - rust:latest
    networks:
      - actix_api
    volumes:
      - ./:/app
    tty: true
    ports:
      - "8888:8888"
  db:
    image: postgres:16.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - .env.db
networks:
  actix_api:
    driver: bridge

volumes:
  postgres_data: