name: Production backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted
    steps:
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - uses: actions/checkout@v3
      - name: Stop and remove previous container
        run: |
          # Stop the previous container if it's running
          if [ "$(docker ps -q -f name=test-server)" ]; then
            docker stop test-server
          fi
          # Remove the previous container if it exists
          if [ "$(docker ps -aq -f status=exited -f name=test-server)" ]; then
            docker rm test-server
          fi
      - name: Run server
        working-directory: ./server_test
        run: |
          docker build -t test-server .
          docker run -d -p 8888:8888 test-server