name: Production backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted
    steps:
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - uses: actions/checkout@v3
      - name: Stop and remove previous container
        run: |
          #  Stop and remove the previous container with the "app=server_test" label
          docker stop $(docker ps -q --filter "label=app=server_test") || true
          docker rm $(docker ps -aq --filter "label=app=server_test") || true
      - name: Run server
        working-directory: ./server_test
        run: |
          docker build -t test-server .
          docker run -d -p 8888:8888 app=server_test test-server